version: '3'
services: 
    neovim:
        build: ./
        container_name: neovim
        tty: true
        environment:
          TZ: Asia/Tokyo
        volumes:
            # プロジェクトディレクトリの同期
            - ../projects:/usr/projects 
            # nvimの設定を弄った時のために同期しておく
            - ./dotfiles/config/nvim:/root/.config/nvim 
            # LSPなどmasonでインストールするものは立ち上げるたびにインストールされるのでここで永続化
            - ./mason:/root/.local/share/nvim/mason 
            # nvimやLSPのキャッシュ　立ち上げるたびにindex作り直すので永続化
            - ./cache:/root/.cache 
            # treesitterのパーサー 立ち上げる度に消えるので永続化
            - ./parser:/root/.local/share/nvim/lazy/nvim-treesitter/parser
            # github copilotの認証情報を同期してコンテナを作り直すたびに再認証をしなくてよくする
            - ./github-copilot:/root/.config/github-copilot
            # ホストOSで取得したバッテリー状況を共有する 
            - ./batteryStatus.txt:/root/batteryStatus.txt
            # READMEをコンテナ内でも編集できるように
            - ./README.md:/root/README.md
